### ISSUE TITLE
cloneAction step fails on schema validation on toxiproxy 

### ISSUE THREAD

**Issue by efarrokh** [powerfulseal/powerfulseal#319]
Hello. I'm unable to use cloneAction to clone existing deployment for toxiproxy usecase. The issue appears to be in schema validation. I'm using the goldpinger example in minikube to test this tool. 

Partial error reads:

> 2021-02-23 16:06:20 ERROR policy_runner {'config': {'runStrategy': {'runs': 1}}, 'scenarios': [{'name': 'Clone and tc', 'steps': [{'clone': {'source': {'deployment': {'name': 'goldpinger', 'namespace': 'default'}}}}]}]}
2021-02-23 16:06:20 ERROR policy_runner Additional properties are not allowed ('clone' was unexpected)
Failed validating 'additionalProperties' in schema[0]:

> On instance:
    {'clone': {'source': {'deployment': {'name': 'goldpinger',
                                         'namespace': 'default'}}}}
2021-02-23 16:06:20 ERROR __main__ Policy not valid. See log output above.

My completely stripped out action reveals this issue. This was copied from the TC example but the toxiproxy example also has the same issue. 

```
config:
  runStrategy:
    runs: 1
scenarios:
- name: Clone and tc
  steps:
  - clone:
      source:
        deployment:
          name: goldpinger
          namespace: default
```

Would really appreciate your help.
