### ISSUE TITLE
Wait between scenario runs

### ISSUE THREAD

**Issue by Niksko** [powerfulseal/powerfulseal#346]
It took me an embarrassingly long time to realise that 

```yaml
    config:
      runStrategy:
        minSecondsBetweenRuns: 600
        maxSecondsBetweenRuns: 900
        strategy: "random"
    scenarios:
    - name: Scenario A
    ...
    - name: Scenario B
    ...
```

causes PowerfulSeal to do the following:
1. Randomly select scenario A or B, and run it
2. Immediately select the other scenario and run it
3. Only now wait between 600 and 900 seconds

What I had assumed would happen was:
1. Randomly select scenario A or B, and run it
2. Wait 600 to 900 seconds
3. Select scenario A or B, and run it
4. repeat forever

Would it be useful to add a mode that does this?
